/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.newssearch.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Article model.
 */
public class Article extends CreativeWork {
    /**
     * The number of words in the text of the Article.
     */
    @JsonProperty(value = "wordCount", access = JsonProperty.Access.WRITE_ONLY)
    private Integer wordCount;

    /**
     * Get the number of words in the text of the Article.
     *
     * @return the wordCount value
     */
    public Integer wordCount() {
        return this.wordCount;
    }

}
