/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.newssearch.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TrendingTopics model.
 */
public class TrendingTopics extends Answer {
    /**
     * A list of trending news topics on Bing.
     */
    @JsonProperty(value = "value", required = true)
    private List<NewsTopic> value;

    /**
     * Get a list of trending news topics on Bing.
     *
     * @return the value value
     */
    public List<NewsTopic> value() {
        return this.value;
    }

    /**
     * Set a list of trending news topics on Bing.
     *
     * @param value the value value to set
     * @return the TrendingTopics object itself.
     */
    public TrendingTopics withValue(List<NewsTopic> value) {
        this.value = value;
        return this;
    }

}
