/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.entitysearch.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Airport model.
 */
public class Airport extends CivicStructure {
    /**
     * The iataCode property.
     */
    @JsonProperty(value = "iataCode", access = JsonProperty.Access.WRITE_ONLY)
    private String iataCode;

    /**
     * The icaoCode property.
     */
    @JsonProperty(value = "icaoCode", access = JsonProperty.Access.WRITE_ONLY)
    private String icaoCode;

    /**
     * Get the iataCode value.
     *
     * @return the iataCode value
     */
    public String iataCode() {
        return this.iataCode;
    }

    /**
     * Get the icaoCode value.
     *
     * @return the icaoCode value
     */
    public String icaoCode() {
        return this.icaoCode;
    }

}
