/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.entitysearch.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The MovieTheater model.
 */
public class MovieTheater extends EntertainmentBusiness {
    /**
     * The screenCount property.
     */
    @JsonProperty(value = "screenCount", access = JsonProperty.Access.WRITE_ONLY)
    private Integer screenCount;

    /**
     * Get the screenCount value.
     *
     * @return the screenCount value
     */
    public Integer screenCount() {
        return this.screenCount;
    }

}
