/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.websearch.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines a list of related queries made by others.
 */
public class RelatedSearchesRelatedSearchAnswer extends SearchResultsAnswer {
    /**
     * A list of related queries that were made by others.
     */
    @JsonProperty(value = "value", required = true)
    private List<Query> value;

    /**
     * Get a list of related queries that were made by others.
     *
     * @return the value value
     */
    public List<Query> value() {
        return this.value;
    }

    /**
     * Set a list of related queries that were made by others.
     *
     * @param value the value value to set
     * @return the RelatedSearchesRelatedSearchAnswer object itself.
     */
    public RelatedSearchesRelatedSearchAnswer withValue(List<Query> value) {
        this.value = value;
        return this;
    }

}
