/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.websearch.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines the top-level object that the response includes when the request
 * succeeds.
 */
public class SearchResponse extends Response {
    /**
     * An object that contains the query string that Bing used for the request.
     * This object contains the query string as entered by the user. It may
     * also contain an altered query string that Bing used for the query if the
     * query string contained a spelling mistake.
     */
    @JsonProperty(value = "queryContext", access = JsonProperty.Access.WRITE_ONLY)
    private QueryContext queryContext;

    /**
     * A list of webpages that are relevant to the search query.
     */
    @JsonProperty(value = "webPages", access = JsonProperty.Access.WRITE_ONLY)
    private WebWebAnswer webPages;

    /**
     * A list of images that are relevant to the search query.
     */
    @JsonProperty(value = "images", access = JsonProperty.Access.WRITE_ONLY)
    private Images images;

    /**
     * A list of news articles that are relevant to the search query.
     */
    @JsonProperty(value = "news", access = JsonProperty.Access.WRITE_ONLY)
    private News news;

    /**
     * A list of related queries made by others.
     */
    @JsonProperty(value = "relatedSearches", access = JsonProperty.Access.WRITE_ONLY)
    private RelatedSearchesRelatedSearchAnswer relatedSearches;

    /**
     * The query string that likely represents the user's intent.
     */
    @JsonProperty(value = "spellSuggestions", access = JsonProperty.Access.WRITE_ONLY)
    private SpellSuggestions spellSuggestions;

    /**
     * The date and time of one or more geographic locations.
     */
    @JsonProperty(value = "timeZone", access = JsonProperty.Access.WRITE_ONLY)
    private TimeZone timeZone;

    /**
     * A list of videos that are relevant to the search query.
     */
    @JsonProperty(value = "videos", access = JsonProperty.Access.WRITE_ONLY)
    private Videos videos;

    /**
     * The answer to a math expression or units conversion expression.
     */
    @JsonProperty(value = "computation", access = JsonProperty.Access.WRITE_ONLY)
    private Computation computation;

    /**
     * The order that Bing suggests that you display the search results in.
     */
    @JsonProperty(value = "rankingResponse", access = JsonProperty.Access.WRITE_ONLY)
    private RankingRankingResponse rankingResponse;

    /**
     * Get an object that contains the query string that Bing used for the request. This object contains the query string as entered by the user. It may also contain an altered query string that Bing used for the query if the query string contained a spelling mistake.
     *
     * @return the queryContext value
     */
    public QueryContext queryContext() {
        return this.queryContext;
    }

    /**
     * Get a list of webpages that are relevant to the search query.
     *
     * @return the webPages value
     */
    public WebWebAnswer webPages() {
        return this.webPages;
    }

    /**
     * Get a list of images that are relevant to the search query.
     *
     * @return the images value
     */
    public Images images() {
        return this.images;
    }

    /**
     * Get a list of news articles that are relevant to the search query.
     *
     * @return the news value
     */
    public News news() {
        return this.news;
    }

    /**
     * Get a list of related queries made by others.
     *
     * @return the relatedSearches value
     */
    public RelatedSearchesRelatedSearchAnswer relatedSearches() {
        return this.relatedSearches;
    }

    /**
     * Get the query string that likely represents the user's intent.
     *
     * @return the spellSuggestions value
     */
    public SpellSuggestions spellSuggestions() {
        return this.spellSuggestions;
    }

    /**
     * Get the date and time of one or more geographic locations.
     *
     * @return the timeZone value
     */
    public TimeZone timeZone() {
        return this.timeZone;
    }

    /**
     * Get a list of videos that are relevant to the search query.
     *
     * @return the videos value
     */
    public Videos videos() {
        return this.videos;
    }

    /**
     * Get the answer to a math expression or units conversion expression.
     *
     * @return the computation value
     */
    public Computation computation() {
        return this.computation;
    }

    /**
     * Get the order that Bing suggests that you display the search results in.
     *
     * @return the rankingResponse value
     */
    public RankingRankingResponse rankingResponse() {
        return this.rankingResponse;
    }

}
