/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.customimagesearch.models;


/**
 * Defines a webpage that is relevant to the query.
 */
public class WebPage extends CreativeWork {
}
