/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.imagesearch.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines a rating.
 */
public class Rating extends PropertiesItem {
    /**
     * The mean (average) rating. The possible values are 1.0 through 5.0.
     */
    @JsonProperty(value = "ratingValue", required = true)
    private double ratingValue;

    /**
     * The highest rated review. The possible values are 1.0 through 5.0.
     */
    @JsonProperty(value = "bestRating", access = JsonProperty.Access.WRITE_ONLY)
    private Double bestRating;

    /**
     * Get the mean (average) rating. The possible values are 1.0 through 5.0.
     *
     * @return the ratingValue value
     */
    public double ratingValue() {
        return this.ratingValue;
    }

    /**
     * Set the mean (average) rating. The possible values are 1.0 through 5.0.
     *
     * @param ratingValue the ratingValue value to set
     * @return the Rating object itself.
     */
    public Rating withRatingValue(double ratingValue) {
        this.ratingValue = ratingValue;
        return this;
    }

    /**
     * Get the highest rated review. The possible values are 1.0 through 5.0.
     *
     * @return the bestRating value
     */
    public Double bestRating() {
        return this.bestRating;
    }

}
