/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.autosuggest.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines a response. All schemas that could be returned at the root of a
 * response should inherit from this.
 */
public class Response extends Identifiable {
    /**
     * The URL that returns this resource.
     */
    @JsonProperty(value = "readLink", access = JsonProperty.Access.WRITE_ONLY)
    private String readLink;

    /**
     * The URL To Bing's search result for this item.
     */
    @JsonProperty(value = "webSearchUrl", access = JsonProperty.Access.WRITE_ONLY)
    private String webSearchUrl;

    /**
     * The potentialAction property.
     */
    @JsonProperty(value = "potentialAction", access = JsonProperty.Access.WRITE_ONLY)
    private List<Action> potentialAction;

    /**
     * The immediateAction property.
     */
    @JsonProperty(value = "immediateAction", access = JsonProperty.Access.WRITE_ONLY)
    private List<Action> immediateAction;

    /**
     * The preferredClickthroughUrl property.
     */
    @JsonProperty(value = "preferredClickthroughUrl", access = JsonProperty.Access.WRITE_ONLY)
    private String preferredClickthroughUrl;

    /**
     * The adaptiveCard property.
     */
    @JsonProperty(value = "adaptiveCard", access = JsonProperty.Access.WRITE_ONLY)
    private String adaptiveCard;

    /**
     * Get the URL that returns this resource.
     *
     * @return the readLink value
     */
    public String readLink() {
        return this.readLink;
    }

    /**
     * Get the URL To Bing's search result for this item.
     *
     * @return the webSearchUrl value
     */
    public String webSearchUrl() {
        return this.webSearchUrl;
    }

    /**
     * Get the potentialAction value.
     *
     * @return the potentialAction value
     */
    public List<Action> potentialAction() {
        return this.potentialAction;
    }

    /**
     * Get the immediateAction value.
     *
     * @return the immediateAction value
     */
    public List<Action> immediateAction() {
        return this.immediateAction;
    }

    /**
     * Get the preferredClickthroughUrl value.
     *
     * @return the preferredClickthroughUrl value
     */
    public String preferredClickthroughUrl() {
        return this.preferredClickthroughUrl;
    }

    /**
     * Get the adaptiveCard value.
     *
     * @return the adaptiveCard value
     */
    public String adaptiveCard() {
        return this.adaptiveCard;
    }

}
