/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.visualsearch.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A visual search tag.
 */
public class ImageTag extends Thing {
    /**
     * Display name for this tag. For the default tag, the display name is
     * empty.
     */
    @JsonProperty(value = "displayName", access = JsonProperty.Access.WRITE_ONLY)
    private String displayName;

    /**
     * The bounding box for this tag. For the default tag, there is no bounding
     * box.
     */
    @JsonProperty(value = "boundingBox", access = JsonProperty.Access.WRITE_ONLY)
    private ImageTagRegion boundingBox;

    /**
     * Actions within this tag. The order of the items denotes the default
     * ranking order of these actions, with the first action being the most
     * likely user intent.
     */
    @JsonProperty(value = "actions", access = JsonProperty.Access.WRITE_ONLY)
    private List<ImageAction> actions;

    /**
     * Get display name for this tag. For the default tag, the display name is empty.
     *
     * @return the displayName value
     */
    public String displayName() {
        return this.displayName;
    }

    /**
     * Get the bounding box for this tag. For the default tag, there is no bounding box.
     *
     * @return the boundingBox value
     */
    public ImageTagRegion boundingBox() {
        return this.boundingBox;
    }

    /**
     * Get actions within this tag. The order of the items denotes the default ranking order of these actions, with the first action being the most likely user intent.
     *
     * @return the actions value
     */
    public List<ImageAction> actions() {
        return this.actions;
    }

}
