/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.bing.visualsearch.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A JSON object that contains information about the image to get insights of.
 * Specify this object only in a knowledgeRequest form data.
 */
public class VisualSearchRequest {
    /**
     * A JSON object that identities the image to get insights of.
     */
    @JsonProperty(value = "imageInfo")
    private ImageInfo imageInfo;

    /**
     * A JSON object containing information about the request, such as filters,
     * or a description.
     */
    @JsonProperty(value = "knowledgeRequest")
    private KnowledgeRequest knowledgeRequest;

    /**
     * Get a JSON object that identities the image to get insights of.
     *
     * @return the imageInfo value
     */
    public ImageInfo imageInfo() {
        return this.imageInfo;
    }

    /**
     * Set a JSON object that identities the image to get insights of.
     *
     * @param imageInfo the imageInfo value to set
     * @return the VisualSearchRequest object itself.
     */
    public VisualSearchRequest withImageInfo(ImageInfo imageInfo) {
        this.imageInfo = imageInfo;
        return this;
    }

    /**
     * Get a JSON object containing information about the request, such as filters, or a description.
     *
     * @return the knowledgeRequest value
     */
    public KnowledgeRequest knowledgeRequest() {
        return this.knowledgeRequest;
    }

    /**
     * Set a JSON object containing information about the request, such as filters, or a description.
     *
     * @param knowledgeRequest the knowledgeRequest value to set
     * @return the VisualSearchRequest object itself.
     */
    public VisualSearchRequest withKnowledgeRequest(KnowledgeRequest knowledgeRequest) {
        this.knowledgeRequest = knowledgeRequest;
        return this;
    }

}
